name: outfit-transformer
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - pillow==11.0.0
    - transformers==4.48.3
    - scikit-learn
    - faiss-cpu
    - wandb
    - tqdm
    - gradio
    - opencv-python 