name: outfit-transformer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - torch==2.3.0
    - torchvision==0.18.0
    - torchaudio==2.3.0
    - pillow==11.0.0
    - transformers==4.48.3
    - scikit-learn
    - faiss-cpu
    - tqdm
    - wandb
    - gradio
    - opencv-python